import fs from 'fs';
import path from 'path';
import { FormConfig, FormMainConfig } from 'src/domain/types';
import { copyPhpFolder } from '../utils/copyPhpFolder';
import { generatePhpFromConfig } from '../utils/generatePhpFromConfig';
import { loadConfig } from '../utils/loadConfig';

export default async function generate() {
  console.log('🚀 Running formpipe generate...\n');

  const projectRoot = process.cwd();
  const config: FormMainConfig = loadConfig();

  // Find the php folder inside the package
  const packagePhpFolder = findPackagePhpFolder(__dirname);
  const projectPhpFolder = path.join(projectRoot, 'php');
  const projectPhpMainFile = path.join(projectPhpFolder, 'contact-form.php');

  try {
    await copyPhpFolder(packagePhpFolder, projectPhpFolder);
    console.log(`✅ Copied PHP folder to:\n   ${projectPhpFolder}`);

    generatePhpFromConfig(config, projectPhpMainFile);
    console.log(`✅ Generated PHP form:\n   ${projectPhpMainFile}\n`);

    const rulesAndPath: FormConfig = {
      rules: config.rules,
      endPointPath: config.endPointPath,
    };
    generateConfigToExport(rulesAndPath, projectPhpFolder);
    console.log(`✅ Generated confit.ts at:\n   ${projectPhpMainFile}\n`);
  } catch (error) {
    console.error('❌ Error during generation:', error);
    process.exit(1);
  }
}

function generateConfigToExport(config: FormConfig, projectPhpFolder: string) {
  const configContent = `
  // This file was generated by the formpipe CLI
  // Do not edit this file manually, edit the formpipe.config.json file instead and run the formpipe generate command again
  // This way you can keep your backend and frontend rules in sync

  import type { FormConfig } from '@formpipe/contact-form';
  export const formConfig: FormConfig = ${JSON.stringify(config, null, 2)};`;
  const configPath = path.join(projectPhpFolder, 'form-config.ts');
  fs.writeFileSync(configPath, configContent);
}

/**
 * Find the root folder of the formpipe package recursively
 * and return the path to /php
 */
function findPackagePhpFolder(startDir: string): string {
  let dir = startDir;

  while (true) {
    const pkgPath = path.join(dir, 'package.json');
    if (fs.existsSync(pkgPath)) {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
      if (pkg.name && pkg.name.startsWith('@formpipe/')) {
        return path.resolve(dir, 'dist/php');
      }
    }

    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }

  throw new Error(
    '❌ Could not locate @formpipe package root to copy /php folder.'
  );
}
